name: fpga-tool-perf-env
channels:
  - conda-forge
  - symbiflow
dependencies:
  - yosys
  - yosys-plugins
  - vtr=8.0.0.rc2_3935_g7d6424bb0
  - nextpnr-xilinx
  - nextpnr-ice40
  - prjxray
  - pip
  - pip:                            # Packages installed from PyPI
    - -r file:requirements.txt
